export const countries = [
  { name: "España", code: "ES", emoji: "🇪🇸" },
  { name: "Estados Unidos", code: "US", emoji: "🇺🇸" },
  { name: "México", code: "MX", emoji: "🇲🇽" },
  { name: "Argentina", code: "AR", emoji: "🇦🇷" },
  { name: "Colombia", code: "CO", emoji: "🇨🇴" },
  { name: "Brasil", code: "BR", emoji: "🇧🇷" },
  { name: "Chile", code: "CL", emoji: "🇨🇱" },
  { name: "Perú", code: "PE", emoji: "🇵🇪" },
  { name: "Ecuador", code: "EC", emoji: "🇪🇨" },
  { name: "Venezuela", code: "VE", emoji: "🇻🇪" },
  { name: "Uruguay", code: "UY", emoji: "🇺🇾" },
  { name: "Paraguay", code: "PY", emoji: "🇵🇾" },
  { name: "Bolivia", code: "BO", emoji: "🇧🇴" },
  { name: "Costa Rica", code: "CR", emoji: "🇨🇷" },
  { name: "Panamá", code: "PA", emoji: "🇵🇦" },
  { name: "Cuba", code: "CU", emoji: "🇨🇺" },
  { name: "Puerto Rico", code: "PR", emoji: "🇵🇷" },
  { name: "República Dominicana", code: "DO", emoji: "🇩🇴" },
  { name: "Honduras", code: "HN", emoji: "🇭🇳" },
  { name: "Guatemala", code: "GT", emoji: "🇬🇹" },
  { name: "El Salvador", code: "SV", emoji: "🇸🇻" },
  { name: "Nicaragua", code: "NI", emoji: "🇳🇮" },
  { name: "Canadá", code: "CA", emoji: "🇨🇦" },
  { name: "Reino Unido", code: "GB", emoji: "🇬🇧" },
  { name: "Francia", code: "FR", emoji: "🇫🇷" },
  { name: "Alemania", code: "DE", emoji: "🇩🇪" },
  { name: "Italia", code: "IT", emoji: "🇮🇹" },
  { name: "Portugal", code: "PT", emoji: "🇵🇹" },
  { name: "Japón", code: "JP", emoji: "🇯🇵" },
  { name: "China", code: "CN", emoji: "🇨🇳" },
  { name: "Corea del Sur", code: "KR", emoji: "🇰🇷" },
  { name: "India", code: "IN", emoji: "🇮🇳" },
  { name: "Australia", code: "AU", emoji: "🇦🇺" },
  { name: "Sudáfrica", code: "ZA", emoji: "🇿🇦" },
  { name: "Egipto", code: "EG", emoji: "🇪🇬" },
  { name: "Turquía", code: "TR", emoji: "🇹🇷" },
  { name: "Rusia", code: "RU", emoji: "🇷🇺" },
  { name: "Filipinas", code: "PH", emoji: "🇵🇭" },
  { name: "Indonesia", code: "ID", emoji: "🇮🇩" },
  { name: "Tailandia", code: "TH", emoji: "🇹🇭" },
  { name: "Pakistán", code: "PK", emoji: "🇵🇰" },
];
